package:
  name: lightningsim
  version: "0.1.0"

source:
  path: ..

build:
  number: 1
  entry_points:
    - lightningsim = lightningsim.main:main
  script_env:
    - CCACHE_DIR

requirements:
  build:
    - {{ compiler('cxx') }}
    - ccache=4
    - clang=15.0.5
    - cmake=3
    - ninja=1
    - nodejs=18
    - sysroot_{{ target_platform }}=2.17     # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - python
    - pip
    - libedit
    - libxml2
    - ncurses
    - zlib
    - zstd

  run:
    - python
    - jinja2
    - llvmlite
    - pyelftools
    - python-socketio
    - uvicorn-standard
    - binutils
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_{{ target_platform }}=2.17     # [linux]

test:
  imports:
    - lightningsim.main

about:
  home: https://github.com/sharc-lab/LightningSim
  license: AGPL-3.0-only
  summary: A fast, accurate trace-based simulator for High-Level Synthesis.
