[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lightningsim"
authors = [
    {name = "Rishov Sarkar", email = "rishov.sarkar@gatech.edu"},
]
version = "0.0.3"
