name: lightningsimv2-benchmarks
channels:
  - https://sharc-lab.github.io/LightningSim/repo
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - lightningsim
  - lightningsimv2
  - blessed
  - time
